### ISSUE TITLE
Loader.js Problem

### ISSUE THREAD

**Issue by frkngksl** [Tylous/ZipExec#4]
Hi,

Sometimes some loader.js's cannot unzip the file, while loader.js is executed via cscript.exe. However, in this case, I can see the zip file under the %TMP% directory. For another case, I can confirm that loader.js is working in my computer properly, but it doesn't work for another computer with the same build number and OS. In the second case, I am getting the same error. The screenshot of the given error can be seen below:

![image](https://user-images.githubusercontent.com/26549173/141119779-dad7b224-bf9c-4337-9c7f-e5053fb3491c.png)

**Comment by Tylous** [comment]
I need more information as to what's going on?

**Comment by Tylous** [comment]
In the process of creating the issue to see why this is happening

**Comment by Tylous** [comment]
I haven't been able to recreate this fully. My best guess is that whatever your zip the A/V EDR on there is seeing something that's preventing the COM object from completing the operation.
