### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by cartiiii** [Tylous/ZipExec#5]
Malicious File: Dark Comet Trojan

nothing happens when running loader.js

should i use a meterpreter shell or something?

**Comment by Tylous** [comment]
It looks like it's flagging on the embedded file. Just by [Googling](https://en.wikipedia.org/wiki/DarkComet) Dark Comet is highly IoCed so it might be that. I would try something more evasive.

**Comment by Tylous** [comment]
Closing due to lack of response.
