### ISSUE TITLE
No se visualiza el archivo loader.js

### ISSUE THREAD

**Issue by jccarideveloper** [Tylous/ZipExec#7]
Se ejecuta la siguiente instrucción
ZipExec -I shell.exe -O loader.js -sandbox
y lo único que devuelve es shell.rar 
El archivo loader.js no se genera, y me surge una duda si se dice que ejecuta binarios 
sin descomprimir. Cuál es la instrucción?

Gracias de antemano, parece interesante, sólo que no hay mucha documentación al respecto.

**Comment by Tylous** [comment]
not sure how you are getting shell.rar it shouldn't be a rar file.

**Comment by Tylous** [comment]
Closing due to lack of response. Feel free to reopen if this in the future if it re-occurs.
