### ISSUE TITLE
Cryptor

### ISSUE THREAD

**Issue by sly9it** [Tylous/ZipExec#9]
Any assistance to changing the cryptor pattern or stub

**Comment by Tylous** [comment]
Can you provide more details?

**Comment by Tylous** [comment]
Are you fighting against Defender

**Comment by sly9it** [comment]
Yes, I am!

**Comment by sly9it** [comment]
Defender is hectic im unable to redesign the crypto though i dont
understand go but ive been learning

**Comment by sly9it** [comment]
Hello tried it on windows 10 and it doesnt work parses an error



# windows cannot complete extraction the destination file could not be created

**Comment by sly9it** [comment]
Any ideas to this

**Comment by sly9it** [comment]
Actually it isnt a defender issue it just has issues smuggling a file on an updated windows 10 

If you could run some tests to view those errors that would be fine

**Comment by Tylous** [comment]
I will test it out and get back to you.

**Comment by sly9it** [comment]
Thanks alot

**Comment by Tylous** [comment]
works just find when I use calc.exe. I believe it is your payload. 

![image](https://user-images.githubusercontent.com/15052743/177806943-57c9c019-8cd2-428c-9772-b022ed7d97fe.png)
